#!/bin/bash

function download() {
    url=$1
    dest=$2

    response=$(curl -X GET ${url} -o -)
    format=$(echo ${response} | jq -r .format)
    if [ "${format}" = "base64" ] ; then
        echo ${response} | jq -j .content | base64 -d > $dest
    elif [ "${format}" = "text" ] ; then
        echo ${response} | jq -j .content > $dest
    else
        echo "Format ${format} of file ${dest} not supported"
        echo ${response} | jq -j .content > $dest
    fi
}

notebook_created="no"

function get_notebook() {
    ## Creates a new notebook if needed. Sets flag to delete if
    ## notebook was re-created.
    apiurl=$1
    sessionid=$2
    serviceid=$3
    svcinfo=`curl --silent -X GET "${apiurl}/${serviceid}" -H  "accept: application/json"`
    if [ $(echo ${svcinfo} | jq -j .sessionId) = "${sessionid}" ] ; then
        return ## NOTEBOOK_URL unchanged.
    fi
    
    svcinfo=`curl --silent -X POST "${apiurl}" -H  "accept: application/json" \
                  -H  "Content-Type: application/json" -d "{\"sessionId\":\"${sessionid}\"}"`
    notebook_created="yes"
    
    svcurl=`echo ${svcinfo} | jq -j .serviceURL`
    if [ "${svcurl}" = "null" ] ; then
        echo "Session ${sessionid} no longer exists. Cannot download data."
        exit 1
    fi

    SERVICE_ID=`echo ${svcinfo} | jq -j .id`
    echo "Wait for service ${SERVICE_ID} to be re-created at ${svcurl}."
    while ! curl --silent -IL -X GET ${svcurl} | grep "200 OK" ; do
        sleep 5
    done
    NOTEBOOK_URL=${svcurl}
}

function delete_notebook() {
    apiurl=$1
    if [ "${notebook_created}" = "yes" ] ; then
        curl -X DELETE "${apiurl}/${SERVICE_ID}" -H  "accept: */*"
    fi
}

function download_working_dir_data() {
    if [ ! -e download_filelist.dat ] ; then
        echo "Nothing to download from working dir."
        return
    fi
    apiurl=$1
    for file in `cat download_filelist.dat` ; do
        download ${apiurl}/${file} ${HOME}/${file}
    done
}

conda install -y -c conda-forge curl jq || exit 1


# =======================================================
# Everything below here is generated by the snapshot job:
# =======================================================
NOTEBOOK_URL=https://swirrl.climate4impact.eu/swirrl/jupyter/17d2feba-c93c-4545-b40b-4eb5fe287153
SERVICE_ID=17d2feba-c93c-4545-b40b-4eb5fe287153
get_notebook http://swirrl-api/swirrl-api/v1.0/notebook 165eb618-2f23-41d5-ba39-eac6101b8aea 17d2feba-c93c-4545-b40b-4eb5fe287153
mkdir -p ~/data/staginghistory/stage.00001
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_201501-201912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_201501-201912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_206001-206412.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_206001-206412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_209501-209912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_209501-209912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_205501-205912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_205501-205912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_202001-202412.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_202001-202412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_208001-208412.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_208001-208412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_203501-203912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_203501-203912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_207501-207912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_207501-207912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_204001-204412.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_204001-204412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_210001-210012.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_210001-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_207001-207412.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_207001-207412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_202501-202912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_202501-202912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_203001-203412.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_203001-203412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_206501-206912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_206501-206912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/swirrl_fileinfo.json ~/data/staginghistory/stage.00001/swirrl_fileinfo.json
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_204501-204912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_204501-204912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_209001-209412.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_209001-209412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_205001-205412.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_205001-205412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_208501-208912.nc ~/data/staginghistory/stage.00001/ta_AERmonZ_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_208501-208912.nc
ln -s ~/data/staginghistory/stage.00001 ~/data/latest
download_working_dir_data ${NOTEBOOK_URL}/api/contents
delete_notebook http://swirrl-api/swirrl-api/v1.0/notebook
